services:
  node:
    build:
      context: .
      dockerfile: ./Development
    restart: "no"
    ports:
        - 3000:3000
    tty: true
    volumes:
      - .:/app/
  db:
    image: postgres:14.3
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
