services:
  prod:
    build:
      context: .
      dockerfile: ./Production
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
    depends_on:
      - db
    ports:
      - 80:80
  db:
    image: postgres:14.3
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data